######################## default configuration ####################
baseURL = "https://sunfashion.netlify.app/"
title = "Sun Fashion | Ethnic wear store"

languageCode = "en-us"
DefaultContentLanguage = "en"
#theme = "hargo"
summaryLength = "20"
paginate = 10

enableEmoji = true
enableRobotsTXT = true
canonifyURLs = true
disqusShortname = ""

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "plugins/google-map/gmap.js"

  
############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "Products"
  URL = "products"
  weight = 1
  
  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 2
  
  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 3
  
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 4

  ############# footer menu #############
  [[menu.footer]]
  name = "Products"
  URL = "products"
  weight = 1
  
  [[menu.footer]]
  name = "Blog"
  URL = "blog"
  weight = 2
  
  [[menu.footer]]
  name = "FAQ"
  URL = "faq"
  weight = 3
  
  [[menu.footer]]
  name = "Terms & Conditions"
  URL = "terms-conditions"
  weight = 4
  
  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 5

#################### language ##########################################
[languages]
  [language.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1

#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
sitename = "Sun Fashion"
facebook = "https://www.facebook.com/SunFashionNLifestyle/"

# Meta data
description = "cotton dress material suit material ladies suit ethinc wear salwar kameez chudidar patiyala"
author = "Sun Fashion"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
# Google Analitycs, create new property
googleAnalitycsID = "UA-87351575-3" # Your ID
# Contact Information
mobile = "9820927720"
email = "sunfashionandlifestyle@gmail.com"
location = "Surat, Gujarat, India"
# copyright
copyright = "| Copyright &copy; 2020 Sun Fashion All Rights Reserved |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Product Rating
  # it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
  [params.rating]
  enable = true
  websiteID = "444334"
  publicKey = "811cf0927332bf51f2e12f84608594ac"

  # Social Site
  [[params.social]]
  icon = "ti-facebook"
  link = "https://www.facebook.com/SunFashionNLifestyle/"
  
  [[params.social]]
  icon = "ti-twitter-alt"
  link = "#"
	
  [[params.social]]
  icon = "ti-youtube"
  link = "#"
  
  [[params.social]]
  icon = "ti-instagram"
  link = "https://www.instagram.com/sun_.fashion/"
  
  [[params.social]]
  icon = "ti-pinterest"
  link = "https://in.pinterest.com/sun_fashion/"

  # Contact Form
  [params.contact]
  formAction = "#" # contact form works with formspree.io
