
backend:
  # test-repo for local testing, replace with git-gateway for deployment
  # name: test-repo
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented, save as draft option available
publish_mode: editorial_workflow

media_folder: "assets/images/products" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/products" # The src attribute for uploaded media will begin with /images/uploads

site_url: https://www.sunfashion.store
display_url: https://www.sunfashion.store
logo_url: https://www.sunfashion.store/images/logo.jpeg
locale: "en"

show_preview_links: true

editor:
  preview: true

collections:
  - name: "product" # Used in routes, e.g., /admin/collections/blog
    label: "New Product" # Used in the UI
    folder: "content/products" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: Product ID, 
          name: productID, 
          widget: string, 
          default: "0025", 
          required: true,
          hint: 4 digit value eg- 0023}

      - { label: Date, 
          name: date, 
          widget: datetime, 
          dateFormat: YYYY-MM-DD, 
          timeFormat: HH:mm:ss, 
          required: true }

      - { label: Type, 
          name: type, 
          widget: string, 
          default: products, 
          required: true,
          hint: must be "products"}

      - { label: Images, 
          name: images, 
          widget: list, 
          collapsed: true,
          summary: '{{fields.image}}',
          required: true,
          hint: first image will be shown in the product page,
          field: {label: Image, name: image, widget: image, required: true} }

      - { label: Video ID,
          name: videoID,
          widget: string,
          required: false,
          hint: only video id eg- 5Y35yjJfC2U; applied to last image}

      - { label : Price,
          name: price,
          widget: number,
          required: true,
          hint: Final price eg- 560,
          default: 560}

      - { label : PriceBefore,
          name: priceBefore,
          widget: number,
          required: false,
          hint: Final price eg- 999; will be slashed; keep blank if not required,
          default: 999}

      - { label: Title, 
          name: title, 
          widget: string, 
          required: true,
          hint: Shown in product page eg- Jaam cotton salwar suit Design '#'25 }

      - { label: URL,
          name: url,
          widget: string,
          required: true,
          hint: Shown as product url eg- Jaam cotton salwar suit with cotton salwar wholesale design25 wholesale}

      - { label: Meta Description,
          name: description,
          widget: string,
          required: true,
          hint: Shown in product list page and google search eg- Jaam cotton dress material with work dupatta; 2.10 mtr cotton salwar}

      - { label: Short Description,
          name: shortDescription,
          widget: text,
          required: true,
          hint: Shown in product single page eg- Beautiful jaam cotton dress material with work dupatta and 2.10 mtr cotton salwar}

      - { label: Draft,
          name: draft,
          widget: boolean,
          default: true}

      - { label: Content,
          name: body,
          widget: markdown}
